services:
  tahfidz-overlay:
    build: .
    container_name: tahfidz-overlay
    ports:
      - "8000:8000"
    environment:
      - DOCKER_RUNNING=true
    restart: unless-stopped
    volumes:
      - .:/app
